### ISSUE TITLE
Upload jsign to Maven Central

### ISSUE THREAD

**Issue by caarlos0** [ebourg/jsign#17]
Hi, nice work!

It would be nice to push the jar to some maven repository... 

Any plans on doing that?

Thanks!

**Comment by ebourg** [comment]
I can upload jsign to Maven Central if you need it.

**Comment by caarlos0** [comment]
@ebourg that would be great :dancer:

**Comment by nedtwigg** [comment]
:+1:  +1

**Comment by caarlos0** [comment]
@ebourg any ETA?

**Comment by ebourg** [comment]
Pending : https://issues.sonatype.org/browse/OSSRH-20874

**Comment by nedtwigg** [comment]
Anything I can do to help with this issue?  With RFC3161 completed, it seems like perhaps a good time.

**Comment by ebourg** [comment]
I'm implementing the handling of multiple signatures and I'll then publish the 1.3 release.

**Comment by nedtwigg** [comment]
Sounds good, thanks very much.  I'm generally a proponent of publishing work as soon as useful pieces are done rather than waiting for all pieces to be done, but if the deployment process is painful then it makes sense to wait until everything is all set.

If you'd like a hand setting up a pipeline which publishes every successful build as a snapshot to oss-snapshots, then auto-promotes tags to mavencentral, [I've done that before](https://github.com/diffplug/durian/blob/3402bbcc84489d67cf2ae3b69cb50a785646ba4e/.ci/ci.sh) and I'd be happy to help.  My email is in my profile.

**Comment by ebourg** [comment]
I haven't added the necessary bits in pom.xml to publish to Maven Central yet. I'd be glad to get a PR with the required modifications.
